#!/bin/bash
# Quick Setup Checklist for Google Sheets Database

echo "📊 Millionaires Club - Google Sheets Setup Checklist"
echo "=================================================="
echo ""
echo "✅ Step 1: Create Google Sheet"
echo "   - Go to sheets.google.com"
echo "   - Create new spreadsheet"
echo "   - Name: 'Millionaires Club Database'"
echo ""
echo "✅ Step 2: Create Sheets (tabs)"
echo "   - Members"
echo "   - Loans"
echo "   - Transactions"  
echo "   - Applications"
echo ""
echo "✅ Step 3: Create Google Apps Script"
echo "   - Open your Sheet"
echo "   - Click Extensions > Apps Script"
echo "   - Copy code from backend/google-apps-script.js"
echo "   - Deploy as Web App"
echo "   - Copy deployment URL"
echo ""
echo "✅ Step 4: Update sheetService.ts"
echo "   - Open services/sheetService.ts"
echo "   - Replace SHEET_API_URL with your deployment URL"
echo ""
echo "✅ Step 5: Start App"
echo "   - Run: npm install"
echo "   - Run: npm run dev"
echo "   - Visit: http://localhost:3000"
echo ""
echo "✅ Step 6: Test Sync"
echo "   - Log in as admin"
echo "   - Click 'Bulk Sync Members' button"
echo "   - Check Google Sheet for data"
echo ""
echo "Done! 🎉"
